language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: python -m unittest discover
notifications:
  slack:
    secure: j8g2Y65tE6xGF0whZcFgkkGiOrXvFE96G8SmPGLEM/VrV6jbeA9Ud+RNxfSmzjwcl2PqRjE6fAMXTmyH0mNlHn6K++MX+AmYa4ntCy5Q9NtK10C/dAi1Aj2pg54U5BcixIctVGw9BXthfC7M4h64BI/Gc8mvtit2HB7YSvdrYq6DOauTGVDBkMdKdEaeG20MdxRwXK0uzCnVrR1p1qzoZ4sT77DvvH8mKbdC0os8/jOxK2yVwWMMHRXF32hbviofOw7hM7SNgSADgmr/per4n+H0QEEfrdCzbKKcZMpqjYKzuvMwFpmPlyAfyrL5R7p5qIW3FIw6wdcFEeqI7FnyfalU7hUTvSseX0/s6gOdiVfzBlcAytFTvxqt4O9lwRtjuJnykEeI3E5duWbFxj3j1eJBrMREXtrfr+xLF2Mf5N1gjmSIm7viHDQjLTkrmvqrOWKfiyqZD/1KNK8XUdNVba7AO3UAfUCk3SCux1VvtWojDer3fJCgZ6HC35p4L1KZUxCErHYY9nSq7YbuAWHBxYM3D8koKNk6VSzbJf4r8qTrHZEr0LADjdH1Gd7GoCa4pda6ko6dlImcRQ8Zq0TfPq71XxNTeL/l5BdmZyqTwjk4UQTk5FF37K8aUgv7XwrLNDy5ChCejwzGYIg//zxUScg7xYSn4pl8Ql6eT32rqrU=
